# Generated by Django 4.2.3 on 2023-09-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Student', models.CharField(max_length=50)),
                ('ID', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('RenterMail', models.EmailField(max_length=254)),
                ('Date', models.DateField()),
                ('Contact', models.CharField(max_length=10)),
            ],
        ),
    ]
